#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# # # # # # #

name: OpenWrt-Lienol-Compile

on:
  push:
    branches: 
      - master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]

env:
  REPO_URL: https://github.com/Lienol/openwrt
  REPO_BRANCH: dev-master #dev-19.07
  CONFIG_FILE: Lienol.config

jobs:

  build_openwrt:

    name: Build OpenWrt and release
    runs-on: ubuntu-18.04

    steps:
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          
    - name: Clone source code
      env: 
        REPO_URL: https://github.com/Lienol/openwrt
        REPO_BRANCH: dev-master
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH --depth=1 openwrt
    
    - name: Custome packages
      run: |
        cd openwrt/package
        mkdir openwrt-packages
        cd openwrt-packages

        # Add themes
        git clone --depth=1 https://github.com/Leo-Jo-My/luci-theme-opentomcat.git
        
        # hello world
        #git clone --depth=1 https://github.com/fw876/helloworld
        
        # hello world another source
        git clone --depth=1 https://github.com/kenzok8/openwrt-packages.git
      
    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a
    
    - name: Clone Config
      env: 
        REPO_URL: https://github.com/showjim/Openwrt-Compile
      run: git clone --depth 1 $REPO_URL openwrt-config
    
    - name: Custom configure file
      run: |
          cd openwrt
          rm -f .config
          cp ../openwrt-config/Lienol.config .config
          
    - name: Make Defconfig
      run: |
          cd openwrt
          make defconfig
          
    - name: Make download
      run: |
          cd openwrt
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
          
    - name: Multi-thread compile
      run: |
          cd openwrt
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
          
    - name: Single-thread compile
      if: failure()
      run: |
          cd openwrt
          make -j1 V=s
          
    - name: Assemble artifact
      run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find openwrt/bin/targets/ -name "*sysupgrade*bin*" | xargs -i mv -f {} ./artifact/
          find openwrt/bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./artifact/
          
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt firmware Lienol
        path: ./artifact/
